server:
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 1996
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl:
        auto: update
    sql:
      init:
        mode: always

  jackson:
    default-property-inclusion: NON_NULL
  sql:
    init:
      platform: postgres

secret:
  key: ${JWT_SECRET:123abc}