server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:veiculosdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl:
        auto: update
    sql:
      init:
        mode: always

  h2:
    console:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL

secret:
  key: ${JWT_SECRET:1234567890qwertyuiop}